---
title: "Neural Network FINAL"
author: "Ajinkya Zalkikar"
date: "11/29/2021"
output: word_document
editor_options: 
  chunk_output_type: console
---
```{r}
setwd("C:/ALL FILES/ISEN/SPRING 21/Research Project/1. Fluid Hammer Effect Project/RAMS Paper Drafts/Spreadsheets")
newdat=read.csv(file="projectfinal.csv")
library(ISLR)
library(glmnet)
set.seed(1)
attach(newdat)
```


```{r}
normal=function(x){return((x-min(x))/(max(x)-min(x)))}
normdat=as.data.frame(lapply(newdat,normal))
training=sample(5000,4000)
train=normdat[training,]
test=normdat[-training,]
train2=newdat[training,]
test2=newdat[-training,]
```

```{r}
library(neuralnet)
BPNN=neuralnet(surge~flow+velo+dia+t+mat,data=train,hidden=c(4,2),linear.output = TRUE, threshold = 0.001,stepmax = 1e+06)
plot(BPNN,rep="best")
```

```{r}
pred=predict(BPNN,newdata=test)
results=data.frame(actual= test$surge, prediction = pred)
predicted=results$prediction*abs(diff(range(surge)))+min(surge)
actual=results$actual*abs(diff(range(surge)))+min(surge)
sqrt(mean((actual-predicted)^2))
```

```{r}
library(neuralnet)
BPNN2=neuralnet(burst~dep+len+dia+t+mat,data=train,hidden=c(4),linear.output = TRUE, threshold = 0.05,stepmax = 1e+06)
plot(BPNN2,rep="best")
```

```{r}
pred2=predict(BPNN2,newdata=test)
results2=data.frame(actual2= test$burst, prediction2 = pred2)
predicted2=results2$prediction2*abs(diff(range(burst)))+min(burst)
actual2=results2$actual2*abs(diff(range(burst)))+min(burst)
sqrt(mean((actual2-predicted2)^2))
```

```{r}
library(neuralnet)
BPNN3=neuralnet(STATUS~dep+len+dia+t+mat+flow+velo,data=train,hidden=c(5),linear.output = FALSE, threshold = 0.05,stepmax = 1e+06)
plot(BPNN3,rep="best")
```

```{r}
pred=predict(BPNN3,newdata=test)
tableNN=table(test$STATUS,apply(pred,1,which.max))
tableNN
```

```{r}
pred3=predict(BPNN3,newdata=test)
tableNN=table(test$STATUS==1,pred[,1]>0.5)
tableNN
accuracy=sum(diag(tableNN))/sum(tableNN)
accuracy
```